name: electricity_monitoring_app
description: "A new Flutter project for managing electricity usage and monitoring."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase packages
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  
  # UI packages
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  fl_chart: ^1.0.0
  intl: ^0.20.2
  
  # PDF and file handling
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.5.10
  
  # Local storage
  shared_preferences: ^2.2.3
  
  # State management
  provider: ^6.1.1
  
  # Animations
  lottie: ^3.0.0
  animated_text_kit: ^4.2.2
  
  # Background processing
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/badges/

